name: CQC First-Run Build

on:
  workflow_dispatch:
    inputs:
      reset_build:
        description: 'Full reset (deletes existing data)'
        required: false
        default: 'false'

jobs:
  first-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main package repo
        uses: actions/checkout@v4
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev
      
      - name: Install R dependencies
        run: |
          R -e 'install.packages(c("httr", "jsonlite", "devtools", "desc"))'
      
      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: Care-Policy-and-Evaluation-Centre/cqc-data-repo
          token: ${{ secrets.CQC_DATA_REPO_TOKEN }}
          path: cqc-data
          ref: main
      
      - name: Reset data repo (if requested)
        if: github.event.inputs.reset_build == 'true'
        working-directory: cqc-data
        run: |
          rm -rf initial_bulk cqc_initial_bulk_*.tar.gz incremental cqc_incremental_*.tar.gz
          echo "Data repo reset"
      
      - name: Create data directories
        run: |
          mkdir -p cqc-data/initial_bulk
          mkdir -p cqc-data/incremental
      
      - name: Run first-build sync
        env:
          R_CQC_API_KEY: ${{ secrets.CQC_API_KEY }}
          CQC_DATA_REPO_PATH: ${{ github.workspace }}/cqc-data
        run: |
          R -f tests/helper-first-build.R
      
      - name: Commit and push data repo
        working-directory: cqc-data
        run: |
          git config user.name "CQC Data Bot"
          git config user.email "noreply@github.com"
          git add -A
          git commit -m "CQC initial bulk download: $(date -u +%Y-%m-%d)" || echo "No changes"
          git push origin main
      
      - name: Commit and push package repo
        run: |
          git config user.name "CQC Data Bot"
          git config user.email "cqc-bot@your-org.com"
          git add DESCRIPTION cqcpack_*.tar.gz
          git commit -m "Initial package build: $(date -u +%Y-%m-%d)" || echo "No changes"
          git push origin main
          